language: csharp
mono: none
solution: EfYou.sln
dotnet: 3.1

before_script: 
- dotnet restore ".\EfYou.sln" 

script: 
- dotnet build ".\EfYou.sln" -c Release 
- dotnet test ".\EfYou.sln" -c Release -v n /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
- dotnet tool install --global coveralls.net --version 1.0.0
- export PATH="$PATH:/home/travis/.dotnet/tools"
- csmacnz.Coveralls --opencover -i /EfYouTests/coverage.opencover.xml --useRelativePaths --commitId $TRAVIS_COMMIT --commitBranch $TRAVIS_BRANCH --commitAuthor "$REPO_COMMIT_AUTHOR" --commitEmail "$REPO_COMMIT_AUTHOR_EMAIL" --commitMessage "$REPO_COMMIT_MESSAGE" --jobId $TRAVIS_JOB_ID  --serviceName travis-ci
